
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: cpp

compiler:
  - gcc

# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. --verbose
  - make
  - ./codecovexample
  - cd ..
  - ./get_code_cov.sh
  
after_success: 
  # Uploading report to CodeCov
  #- bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
